name: "Network-Config-Test"
x-type: "hlfv1"
description: "The network used in the integration tests"
version: 1.0.0

client:
  organization: OrgA
  credentialStore:
    path: "/tmp/hfc-kvs"
    cryptoStore:
      path: "/tmp/hfc-cvs"
    wallet: wallet-name

channels:
  txchannel:
    orderers:
      - Orderer0
    peers:
      OrgA:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

    chaincodes:
      - bcgiscc:v0.2

organizations:
  OrgA:
    mspid: OrgA
    peers:
      - peer0.orga.example.com

    adminPrivateKey:
        path: E:\crypto-config\peerOrganizations\orga.example.com\users\Admin@orga.example.com\msp\keystore\5e6ed6482a8c1c93d3fc0c1344fc63c8a32a987e79143b3598af1bc4708fe525_sk

    signedCert:
      path: E:\crypto-config\peerOrganizations\orga.example.com\users\Admin@orga.example.com\msp\signcerts\Admin@orga.example.com-cert.pem


orderers:
  Orderer0:
    url: grpcs://orderer0.example.com:7050
    tlsCACerts:
      path: E:\crypto-config\ordererOrganizations\example.com\tlsca\tlsca.example.com-cert.pem
    grpcOptions:
      grpc-max-send-message-length: 15
      grpc.keepalive_time_ms: 360000
      grpc.keepalive_timeout_ms: 180000

peers:
  OrgA:
    url: grpcs://peer0.orga.example.com:7051
    tlsCACerts:
      path: E:\crypto-config\peerOrganizations\orga.example.com\tlsca\tlsca.orga.example.com-cert.pem
    grpcOptions:
      grpc.http2.keepalive_time: 15

